// Generated by gencpp from file clean_robot/GripperControl.msg
// DO NOT EDIT!


#ifndef CLEAN_ROBOT_MESSAGE_GRIPPERCONTROL_H
#define CLEAN_ROBOT_MESSAGE_GRIPPERCONTROL_H

#include <ros/service_traits.h>


#include <clean_robot/GripperControlRequest.h>
#include <clean_robot/GripperControlResponse.h>


namespace clean_robot
{

struct GripperControl
{

typedef GripperControlRequest Request;
typedef GripperControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperControl
} // namespace clean_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clean_robot::GripperControl > {
  static const char* value()
  {
    return "55a3885cd6a0cb48fd314894a776c441";
  }

  static const char* value(const ::clean_robot::GripperControl&) { return value(); }
};

template<>
struct DataType< ::clean_robot::GripperControl > {
  static const char* value()
  {
    return "clean_robot/GripperControl";
  }

  static const char* value(const ::clean_robot::GripperControl&) { return value(); }
};


// service_traits::MD5Sum< ::clean_robot::GripperControlRequest> should match
// service_traits::MD5Sum< ::clean_robot::GripperControl >
template<>
struct MD5Sum< ::clean_robot::GripperControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clean_robot::GripperControl >::value();
  }
  static const char* value(const ::clean_robot::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clean_robot::GripperControlRequest> should match
// service_traits::DataType< ::clean_robot::GripperControl >
template<>
struct DataType< ::clean_robot::GripperControlRequest>
{
  static const char* value()
  {
    return DataType< ::clean_robot::GripperControl >::value();
  }
  static const char* value(const ::clean_robot::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clean_robot::GripperControlResponse> should match
// service_traits::MD5Sum< ::clean_robot::GripperControl >
template<>
struct MD5Sum< ::clean_robot::GripperControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clean_robot::GripperControl >::value();
  }
  static const char* value(const ::clean_robot::GripperControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clean_robot::GripperControlResponse> should match
// service_traits::DataType< ::clean_robot::GripperControl >
template<>
struct DataType< ::clean_robot::GripperControlResponse>
{
  static const char* value()
  {
    return DataType< ::clean_robot::GripperControl >::value();
  }
  static const char* value(const ::clean_robot::GripperControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLEAN_ROBOT_MESSAGE_GRIPPERCONTROL_H
