// Generated by gencpp from file clean_robot/GripperControlResponse.msg
// DO NOT EDIT!


#ifndef CLEAN_ROBOT_MESSAGE_GRIPPERCONTROLRESPONSE_H
#define CLEAN_ROBOT_MESSAGE_GRIPPERCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clean_robot
{
template <class ContainerAllocator>
struct GripperControlResponse_
{
  typedef GripperControlResponse_<ContainerAllocator> Type;

  GripperControlResponse_()
    : result(false)
    , current_angle(0.0)
    , info()  {
    }
  GripperControlResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , current_angle(0.0)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef float _current_angle_type;
  _current_angle_type current_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::clean_robot::GripperControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clean_robot::GripperControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlResponse_

typedef ::clean_robot::GripperControlResponse_<std::allocator<void> > GripperControlResponse;

typedef boost::shared_ptr< ::clean_robot::GripperControlResponse > GripperControlResponsePtr;
typedef boost::shared_ptr< ::clean_robot::GripperControlResponse const> GripperControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clean_robot::GripperControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clean_robot::GripperControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clean_robot::GripperControlResponse_<ContainerAllocator1> & lhs, const ::clean_robot::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.current_angle == rhs.current_angle &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clean_robot::GripperControlResponse_<ContainerAllocator1> & lhs, const ::clean_robot::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clean_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clean_robot::GripperControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clean_robot::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clean_robot::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97b215a2a03506f046ae385e68943d66";
  }

  static const char* value(const ::clean_robot::GripperControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97b215a2a03506f0ULL;
  static const uint64_t static_value2 = 0x46ae385e68943d66ULL;
};

template<class ContainerAllocator>
struct DataType< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clean_robot/GripperControlResponse";
  }

  static const char* value(const ::clean_robot::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#响应：执行结果+当前实际角度+结果说明\n"
"bool result                 #ture=执行成功，false=执行失败\n"
"float32 current_angle       #成功为目标角度，失败为上一帧有效角度\n"
"string info                 #结果说明（角度合法，执行成功/执行失败—角度超出范围/角度变化过小）\n"
;
  }

  static const char* value(const ::clean_robot::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.current_angle);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clean_robot::GripperControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clean_robot::GripperControlResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_angle: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLEAN_ROBOT_MESSAGE_GRIPPERCONTROLRESPONSE_H
